#!/bin/bash

######################################################################
#
#  Copyright (c) 2015 arakasi72 (https://github.com/arakasi72)
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions: 
#
#  The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. 
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#  --> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
######################################################################

PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin

get_scripts() {
local script_name=$1
local script_dest=$2
local attempts=0
local script_size=0
local bindest="/usr/local/bin"

while [ $script_size = 0 ]
  do
    rm -f $script_name
    attempts=$(( $attempts + 1 ))
    if [ $attempts = 20 ]; then
      echo "There is a problem downloading from github. Please check your network or there may be an issue with the github website"
      echo "If the Github website is down, you can try again later"
      exit 1
    fi
    wget --no-check-certificate https://raw.githubusercontent.com/arakasi72/rtinst/master/$script_name
    script_size=$(du -b $script_name | cut -f1)
  done

if ! [ -z "$script_dest" ]; then
  mv -f $script_name $script_dest
  if case $script_dest in *"${bindest}"*) true;; *) false;; esac; then
    chmod 755 $script_dest
  fi
fi
}

lineno=$(sed -n '/include \/etc\/nginx\/conf\.d\/rtdload;/=' /etc/nginx/sites-available/default)

if ! [ "$LOGNAME" = "root" ]; then
  echo "Must be run as root, directly or with sudo"
  exit 1
fi

if [ "$1" = "enable" ]; then
  if ! [ -f /etc/nginx/conf.d/rtdload ]; then
    get_scripts nginxsitedl /etc/nginx/conf.d/rtdload
  fi

  if [ -z "$lineno" ]; then
    sed -i '/location \~ \/\\\.ht/ i\        include \/etc\/nginx\/conf\.d\/rtdload;\n' /etc/nginx/sites-available/default
  else
    sed -i '/rtdload/ c\        include \/etc\/nginx\/conf\.d\/rtdload;' /etc/nginx/sites-available/default
  fi
  service nginx reload
  echo "http download enabled"

elif [ "$1" = "disable" ]; then
  if ! [ -z "$lineno" ]; then
    sed -i '/rtdload/ c\        #include \/etc\/nginx\/conf\.d\/rtdload;' /etc/nginx/sites-available/default
    service nginx reload
  fi
  echo "http download disabled"
else
  echo "argument must be enable or disable"
  exit 1
fi
