#!/bin/bash
PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin

script_list=($(curl -s  https://raw.githubusercontent.com/arakasi72/rtinst/master/script_list))

rt_get_scripts() {
local script_name=$1
local attempts=0
local script_size=0
local bindest="/usr/local/bin"

while [ $script_size = 0 ]
  do
    rm -f /usr/local/bin/$script_name
    attempts=$(( $attempts + 1 ))
    if [ $attempts = 20 ]; then
      echo "There is a problem downloading the scripts. Please check your network or there may be an issue with the github website"
      echo "If the Github website is down, you can try again later"
      exit 1
    fi
    wget -q --no-check-certificate --output-document=/usr/local/bin/$script_name https://raw.githubusercontent.com/arakasi72/rtinst/master/$script_name
    script_size=$(du -b /usr/local/bin/$script_name | cut -f1)
  done

chmod 755 /usr/local/bin/$script_name

}

if [ -z "$SUDO_USER" -a  "$LOGNAME" != "root" ]; then
echo "Must be run from root or using sudo" && exit 1
fi

if [ -f "/var/www/rutorrent/.htpasswd" ]; then
  mv /var/www/rutorrent/.htpasswd /etc/nginx
  chown www-data:www-data /etc/nginx/.htpasswd
  chmod 640 /etc/nginx/.htpasswd
  sed -i 's/\/var\/www\/rutorrent\/\.htpasswd/\/etc\/nginx\/\.htpasswd/g' /etc/nginx/sites-available/default
  sed -i 's/\/var\/www\/rutorrent\/\.htpasswd/\/etc\/nginx\/\.htpasswd/g' /etc/nginx/conf.d/rtdload
  service nginx reload
fi

cd $HOME
for i in "${script_list[@]}"
do
  rt_get_scripts $i
done

echo "Completed scripts download"

if [ -f $HOME/rtgetscripts ]; then
  rm -f $HOME/rtgetscripts
fi
