#!/bin/bash

######################################################################
#
#  Copyright (c) 2015 arakasi72 (https://github.com/arakasi72)
#
#  --> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
######################################################################

PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin
branch=$1

if [ -z $branch ]; then
  branch=master
fi

if [ "$(id -u)" != "0" ]; then
  echo "Must be run as root, directly or with sudo"
  exit 1
fi

if [ $(dpkg-query -W -f='${Status}' git 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
echo "Installing git"
apt-get -yqq install git 2>&1 >> /dev/null
fi

rm -r /etc/rtinst
git clone -b $branch --single-branch https://github.com/arakasi72/rtinst.git /etc/rtinst
ln -sf /etc/rtinst/scripts/* /usr/local/bin
ln -sf /etc/rtinst/rtsetup /usr/local/bin

rundir=$(dirname $(readlink -f $0))
if [ "$rundir" != "/etc/rtinst" ]; then
    rm -f $rundir/rtgetscripts
fi
