#!/bin/bash

if [ ! -z "$1" ]; then
        if [ -z "$(grep "ALL ALL = NOPASSWD: /usr/local/bin/rtsetpass" $1)" ]; then
          echo "ALL ALL = NOPASSWD: /usr/local/bin/rtsetpass" >> $1
        fi
else
        export EDITOR=$0
        visudo
fi
