#!/bin/bash

######################################################################
#
#  Copyright (c) 2015 arakasi72 (https://github.com/arakasi72)
#
#  --> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
######################################################################

PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin

lineno=$(sed -n '/dload-loc/=' /etc/nginx/sites-available/default)

if ! [ "$LOGNAME" = "root" ]; then
  echo "Must be run as root, directly or with sudo"
  exit 1
fi

if [ -f /etc/nginx/conf.d/rtdload ]; then rm -f /etc/nginx/conf.d/rtdload; fi
sed -i '/rtdload/d' /etc/nginx/sites-available/default

if [ $# = 0 ]; then
  rtdgrep1=$(grep dload-loc /etc/nginx/sites-available/default)
  rtdgrep2=$(grep dload-loc /etc/nginx/sites-available/default | grep '#')
  if [ -n "$rtdgrep1" -a -z "$rtdgrep2" ]; then
    echo "Enabled"
  else
    echo "Disabled"
  fi

elif [ "$1" = "enable" ]; then
  if ! [ -f /etc/nginx/sites-available/dload-loc ]; then
    rtgetscripts
    rtgetscripts /etc/nginx/sites-available/dload-loc nginxsitedl
  fi

  if [ -z "$lineno" ]; then
    sed -i '/location \~ \/\\\.ht/ i\        include \/etc\/nginx\/sites-available\/dload-loc;\n' /etc/nginx/sites-available/default
  else
    sed -i '/dload-loc/ c\        include \/etc\/nginx\/sites-available\/dload-loc;' /etc/nginx/sites-available/default
  fi
  service nginx reload
  echo "http download enabled"

elif [ "$1" = "disable" ]; then
  if ! [ -z "$lineno" ]; then
    sed -i '/dload-loc/ c\        #include \/etc\/nginx\/sites-available\/dload-loc;' /etc/nginx/sites-available/default
    service nginx reload
  fi
  echo "http download disabled"
else
  echo "argument must be enable or disable"
  exit 1
fi
