#!/bin/bash

#########################################################################################
#
#  Copyright (c) 2015 arakasi72 (https://github.com/arakasi72)
#
#  --> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
#########################################################################################



osname=$(lsb_release -si)
[ -z $logfile ] && logfile="/dev/null"
if [ -z $serverdn ]; then
  headless=1
fi

#check it is being run as root
if [ "$(id -u)" != "0" ]; then
  echo "Must be run from root or using sudo" && exit 1
fi

if [ $headless = 1 ]; then
  serveripa=$(ip route get 8.8.8.8 | awk 'NR==1 {print $7}')
  serveripb=$(wget -qO- ipecho.net/plain)
  if [ "$serveripa" = "$serveripb" ]; then
    serverip=$serveripa
  else
    echo "Select the IP address to use:"
    echo "1.) "$serveripa
    echo "2.) "$serveripb

    while true
      do
        read answer
        case $answer in [1] ) serverip=$serveripa && break ;;
                        [2] ) serverip=$serveripb && break ;;
                          * ) echo "Enter 1 or 2";;
      esac
    done
  fi
  serverdn=$(perl -MSocket -le "print((gethostbyaddr(inet_aton('$serverip'), AF_INET))[0])")
fi

echo "IP: $serverip"
echo "DN: $serverdn"

if [ -z $serverdn ]; then
  echo "Unable to determine domain cannot setup Lets Encypt"
  exit 1
fi

#Installing Certbot
if [ $(dpkg-query -W -f='${Status}' "certbot" 2>/dev/null | grep -c "ok installed") = 0 ]; then
  echo "Installing certbot"

  if [ "$osname" = "Ubuntu" ]; then
    apt-get -q update >> $logfile 2>&1
    add-apt-repository -y universe >> $logfile 2>&1
    add-apt-repository -y ppa:certbot/certbot >> $logfile 2>&1
    apt-get -q update >> $logfile 2>&1
    apt-get install -y certbot python-certbot-nginx >> $logfile 2>&1
  fi
fi

#Generating Certificates
certbot -q --nginx --register-unsafely-without-email certonly -d $serverdn

if [ $? = 1 ]; then
  echo "unable to generate certificates"
  exit 1
fi

echo "Certificates Generated"

if [ $headless = 0 ]; then
  exit 0
fi




